-- Create a new database
CREATE DATABASE [$(DB_NAME)]
ON PRIMARY
( NAME = N'$(DB_NAME)', FILENAME = N'/var/opt/mssql/data/appdb/$(DB_NAME).mdf' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10% )
LOG ON
( NAME = N'$(DB_NAME)_log', FILENAME = N'/var/opt/mssql/log/appdb/$(DB_NAME)_log.ldf' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10% )
GO

ALTER DATABASE [$(DB_NAME)] SET RECOVERY FULL;
ALTER DATABASE [$(DB_NAME)] SET QUOTED_IDENTIFIER ON;

USE [master]
GO

IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = N'$(DB_USER)')
CREATE LOGIN [$(DB_USER)] WITH PASSWORD=N'$(DB_PASSWORD)', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

USE [$(DB_NAME)]
GO

IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = N'$(DB_USER)')
    BEGIN
        CREATE USER [$(DB_USER)]
        FOR LOGIN [$(DB_USER)] WITH DEFAULT_SCHEMA=[dbo]
    END
GO

ALTER ROLE [db_owner] ADD MEMBER [$(DB_USER)]
GO

PRINT 'SQL SETUP COMPLETE'